# Generated by Django 5.0.1 on 2025-01-06 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_produto_quantidade'),
        ('pedidos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data_pedido']},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='data_atualizacao',
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_aceite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_retirada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.motorista'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('ACE', 'Aceito'), ('RET', 'Retirado'), ('SAI', 'Saiu para entrega'), ('ENT', 'Entregue'), ('CAN', 'Cancelado')], default='PEN', max_length=3),
        ),
    ]
