# Generated by Django 5.0.1 on 2025-01-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_options_remove_pedido_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
