# Generated by Django 5.0.1 on 2025-01-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('pedidos', '0002_alter_pedido_options_remove_pedido_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['enviada_em'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AddField(
            model_name='conversa',
            name='tipo',
            field=models.CharField(choices=[('CLI_EMP', 'Cliente-Empresa'), ('CLI_MOT', 'Cliente-Motorista'), ('MOT_EMP', 'Motorista-Empresa')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='conversa',
            unique_together={('pedido', 'tipo')},
        ),
    ]
