# Generated by Django 5.0.1 on 2025-01-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
    ]
